# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bpmachine}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["fabiokung"]
  s.date = %q{2010-02-01}
  s.description = %q{Includes a DSL for business process specification. The process state is persistent, which allows it to be be resumed if an error occurs.}
  s.email = %q{fabio.kung@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "bpmachine.gemspec",
     "features/bpmachine.feature",
     "features/step_definitions/bpmachine_steps.rb",
     "features/support/env.rb",
     "lib/bpmachine.rb",
     "lib/bpmachine/process_specification.rb",
     "lib/bpmachine/version.rb",
     "spec/bpmachine_spec.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/uninstall_steps.rb",
     "spec/wrong_steps.rb"
  ]
  s.homepage = %q{http://github.com/fabiokung/bpmachine}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Business Process execution engine, with resume support on failures.}
  s.test_files = [
    "spec/wrong_steps.rb",
     "spec/bpmachine_spec.rb",
     "spec/uninstall_steps.rb",
     "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<cucumber>, [">= 0"])
      s.add_development_dependency(%q<spork>, [">= 0"])
    else
      s.add_dependency(%q<activesupport>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<cucumber>, [">= 0"])
      s.add_dependency(%q<spork>, [">= 0"])
    end
  else
    s.add_dependency(%q<activesupport>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<cucumber>, [">= 0"])
    s.add_dependency(%q<spork>, [">= 0"])
  end
end

